[[redirects]]
  from = "/guide/"
  to = "/guide/DZDintroduction.html"

[[redirects]]
 from = "guide/doc-style-guide.html"
 to = "/guide/contributing/doc-style-guide.html"

[[redirects]]
  from = "/guide/writing-guide.html"
  to = "/guide/contributing/writing-guide.html"
